# =============================================================================
# Terraform Variables — Aura Cloud SaaS
# =============================================================================
# Only 4 variables. AWS credentials come from environment variables
# (set as GitHub Secrets: AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY).
# Nothing else needs to be provided manually.
# =============================================================================

variable "aws_region" {
  description = "AWS region to deploy resources in"
  type        = string
  default     = "us-east-1"
  # Override via: TF_VAR_aws_region or --var aws_region=ap-south-1
}

variable "project_name" {
  description = "Short name used to prefix all AWS resources"
  type        = string
  default     = "aura-saas"
}

variable "db_name" {
  description = "Name of the PostgreSQL database to create"
  type        = string
  default     = "crm_db"
}

variable "db_username" {
  description = "PostgreSQL master username"
  type        = string
  default     = "crm_app_user"
  # Password is AUTO-GENERATED by random_password resource in main.tf
  # No need to set this manually anywhere
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)"
  type        = string
  default     = "dev"
}
