name: Cleanup Old Dev
on: workflow_dispatch
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
          terraform_wrapper: false
      - working-directory: terraform
        run: |
          terraform init -backend-config="region=${{ secrets.AWS_REGION }}"
          terraform workspace select dev
          terraform destroy -auto-approve -var-file="environments/dev.tfvars" -var="aws_region=${{ secrets.AWS_REGION }}"
